from transformers import AutoProcessor, AutoModelForSpeechSeq2Seq
from dto.audio_data import AudioData
from logs.logger_singleton import Logger
import torch


class Whisper:
    """
     Whisper local model loader and inference handler.

    Attributes:
        model_details (str): Dictionary containing the model details.
        device (str): Device to load the model on, e.g., 'cuda' or 'cpu'.
        model (AutoModelForSpeechSeq2Seq): Loaded for automatic speech recognition model.
        tokenizer (AutoProcessor): Corresponding tokenizer.
        feature_extractor (AutoProcessor): Correspoiding feature extreactor.
    """

    def __init__(self, model_details: dict, device="cuda", logger=None):
        """
        Initialize the Whisper model loader.

        Args:
            model_details (dict): Model details.
            device (str, optional): Device to load the model on. Defaults to 'cuda'.
            logger (Logger, optional): Logger instance. If None, a default is used.
        """
        self.logger = logger or Logger(self.__class__.__name__)
        self.device = device
        self.cache_dir = model_details.get("location")
        self.model = None
        self.tokenizer = None
        self.feature_extractor = None

    def configure_model(self):
        """
        Configure and load the Whisper.
        """
        try:

            # Load AutoProcessor
            processor = AutoProcessor.from_pretrained(
                self.cache_dir, local_files_only=True
            )

            # Load tokenizer
            self.tokenizer = processor.tokenizer
            self.logger.info("Tokenizer loaded successfully.")

            # Load feature extractor
            self.feature_extractor = processor.feature_extractor
            self.logger.info("Feature Extractor loaded successfully.")

            # Load model
            self.model = AutoModelForSpeechSeq2Seq.from_pretrained(
                self.cache_dir,
                device_map="auto",
                dtype=torch.float16,
                max_memory={0: "4GiB"},
                local_files_only=True,
            )
            self.logger.info("Whisper model successfully loaded.")
        except Exception as e:
            self.logger.error(f"Error loading Whisper model: {e}")
            raise RuntimeError(f"Failed to load Whisper model: {e}")

    def create(self, audio: AudioData) -> str:
        """
        Transcribe audio data to text.

        Args:
            audio (AudioData): An object containing the waveform tensor and sample rate.

        Returns:
            str: The transcribed text generated by the model.
        """

        # Tokenize input
        if not self.model:
            self.logger.info("Model not loaded. Loading now...")
            self.configure_model()

        try:
            # Create input features
            input_features = self.feature_extractor(
                audio.waveform,
                sampling_rate=audio.sample_rate,
                return_tensors="pt",
            ).to(self.device, dtype=torch.float16)

            # Generate output
            output = self.model.generate(
                input_features=input_features,
            ).to(self.device)

            result = self.tokenizer.decode(output[0], skip_special_tokens=True)
            self.logger.info("Response generated successfully.")
            return result

        except Exception as e:
            self.logger.error(f"Error during transcription generation: {e}")
            raise RuntimeError(f"Whisper model generation failed: {e}")
